# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
    # Run every Monday
    schedule:
      interval: "weekly"
      timezone: "Europe/Zurich"
    # Group PRs to avoid having to rebase/merge too many
    groups:
      dependabot:
        patterns:
          - "*"
    # Only care about our direct dependencies
    allow:
      dependency-type: "direct"
    ignore:
      # Filter out semver patches updates to reduce the frequency of updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
