# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    labels:
      - "dependencies"
      - "javascript"
    # Run every Monday
    schedule:
      interval: "weekly"
      timezone: "Europe/Zurich"
    # Group PRs to avoid having to rebase/merge too many
    groups:
      dependabot:
        patterns:
          - "*"
    # Only care about our direct dependencies
    allow:
      - dependency-type: "direct"
    ignore:
      # Filter out semver patches updates to reduce the frequency of updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "depedencies"
      - "CI"
    # Run every Monday
    schedule:
      interval: "weekly"
      timezone: "Europe/Zurich"
    groups:
      dependabot:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        # For github-actions, we only care about major version update
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"

  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
      - "python"
    # Run every Monday
    schedule:
      interval: "weekly"
      timezone: "Europe/Zurich"
    # Group PRs to avoid having to rebase/merge too many
    groups:
      dependabot:
        patterns:
          - "*"
    # Only care about our direct dependencies
    allow:
      - dependency-type: "direct"
    ignore:
      # Filter out semver patches updates to reduce the frequency of updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

