name: pytest
on:
  push:
    paths:
      - '**/*.py'
      - 'pytest.ini'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: 0 5 * * 1 # Every Monday at 5:00 UTC
  merge_group:

jobs:
  unittesting:
    runs-on: ubuntu-22.04
    if: github.event_name != 'schedule'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Installing package
        run: |
          pip install --require-hashes --no-deps -r requirements.txt
          pip install --editable ".[capture,dev,extra]"
      - name: Install workflow dependencies
        run: |
          # Install PS drivers
          wget -O- https://labs.picotech.com/Release.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/picotech-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/picotech-archive-keyring.gpg] https://labs.picotech.com/rc/picoscope7/debian/ picoscope main" | sudo tee /etc/apt/sources.list.d/picoscope7.list
          sudo apt-get update
          sudo apt-get install libps6000a
      - name: Installing picosdk package
        run:
          pip install --upgrade picosdk
      - name: Running unit tests
        run: python -m pytest

  coverage:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Installing package
        run: |
          pip install --require-hashes --no-deps -r requirements.txt
          pip install --editable ".[capture,dev,extra]"
      - name: Install workflow dependencies
        run: |
          # Install PS drivers
          wget -O- https://labs.picotech.com/Release.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/picotech-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/picotech-archive-keyring.gpg] https://labs.picotech.com/rc/picoscope7/debian/ picoscope main" | sudo tee /etc/apt/sources.list.d/picoscope7.list
          sudo apt-get update
          sudo apt-get install libps6000a
      - name: Installing picosdk package
        run:
          pip install --upgrade picosdk
      - name: Install workflow dependencies
        run: pip install --upgrade pytest coverage
      - name: Running unit tests with coverage
        env:
          DISABLE_AUTOGRAPH: 1
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload results
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329
        with:
          file: coverage.xml

  piptest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Make sure not to install from source
        run: rm -rf scaaml/
      - name: Installing package
        run: |
          pip install "scaaml[capture,dev,extra]"
      - name: Install workflow dependencies
        run: |
          # Install PS drivers
          wget -O- https://labs.picotech.com/Release.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/picotech-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/picotech-archive-keyring.gpg] https://labs.picotech.com/rc/picoscope7/debian/ picoscope main" | sudo tee /etc/apt/sources.list.d/picoscope7.list
          sudo apt-get update
          sudo apt-get install libps6000a
      - name: Installing picosdk package
        run:
          pip install --upgrade picosdk
      - name: Running unit tests
        run: python -m pytest tests/io
