name: yapf
on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  yapf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install 'yapf>=0.30.0'
      - name: Test code formatting with yapf
        run: |
          echo ::add-matcher::./.github/python_matcher.json
          yapf --style=google --recursive --diff .
